version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor:
      name: android/android
      sdk-version: '28'

    steps:
      - checkout
      - run:
          name: Assemble outputs
          command: ./gradlew -x lint assembleDebug assembleRelease --parallel

  test:
    executor:
      name: android/android
      sdk-version: '28'

    steps:
      - run:
          name: Run Tests
          command: ./gradlew test --parallel

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test